### ISSUE TITLE
Errors while running circtools_install_R_dependencies

### ISSUE THREAD

**Issue by shubhada-kulkarni** [jakobilab/circtools#2]
Dear Tobias,

I am trying to install the latest circtools installation and I managed to do it using pip install. However, when I try to install the R packages using `circtools_install_R_dependencies` script, I get error related to installation of primex package. The error message is attached below. I am using R version 4.2.1.

```
(base) skulkarni@slurm-c-mk1-5c:/prj/circtools2/installation$ circtools_install_R_dependencies 


This script will automatically install R packages required by circtools.

Detected R version 4.2.1

Detected library paths:
-> /beegfs/homes/skulkarni
-> /beegfs/biosw/R/4.2.1_deb11/lib/R/library

Need to install package aod
Need to install package amap
Need to install package ballgown
Need to install package biomaRt
Need to install package edgeR
Need to install package GenomicFeatures
Need to install package GenomicRanges
Need to install package ggbio
Need to install package ggfortify
Need to install package gplots
Need to install package ggrepel
Need to install package gridExtra
Need to install package openxlsx
Need to install package plyr
Need to install package Hmisc
Need to install package reshape2
Need to install package kableExtra
Need to install package formattable

Installation will start in 10 seconds.
Press ctrl+c to cancel.

 0
Now installing R CircTest and primex R packages.

Installing package into ‘/beegfs/homes/skulkarni’
(as ‘lib’ is unspecified)
ERROR: dependencies ‘GenomicRanges’, ‘BSgenome’, ‘IRanges’, ‘S4Vectors’, ‘Biostrings’ are not available for package ‘primex’
* removing ‘/beegfs/homes/skulkarni/primex’
Warning message:
In install.packages(paste0(base_path, "/contrib/primex"), repos = NULL,  :
  installation of package ‘/home/skulkarni/.local/lib/python3.10/site-packages/circtools/contrib/primex’ had non-zero exit status
Installing package into ‘/beegfs/homes/skulkarni’
(as ‘lib’ is unspecified)
ERROR: dependencies ‘aod’, ‘plyr’ are not available for package ‘CircTest’
* removing ‘/beegfs/homes/skulkarni/CircTest’
Warning message:
In install.packages(paste0(base_path, "/contrib/circtest"), repos = NULL,  :
  installation of package ‘/home/skulkarni/.local/lib/python3.10/site-packages/circtools/contrib/circtest’ had non-zero exit status
```

**Comment by tjakobi** [comment]
Hi @shubhada-kulkarni ,

Just to make sure, how did you install circtools using pip? From pypi or directly from the git repository?

I added a fix in the master branch of this repository, please pull the latest changes and retry the installation.

Best,

Tobias

**Comment by shubhada-kulkarni** [comment]
Hello @tjakobi,

I first installed using pypi, which is when I got this error. Later I tried with git and I got the same error again. 

Now I tried after pulling the latest changes, I still have the same errors. The circtools installation went okay, but installing R packages is giving errors related to dependencies. Please see both output for both commands (python setup.py install and circtools_install_R_dependencies) in attach.

Regards,
Shubhada
[output_circtools2_installation_git_300723.txt](https://github.com/jakobilab/circtools/files/12209244/output_circtools2_installation_git_300723.txt)
[output_circtools2_installation_R_300723.txt](https://github.com/jakobilab/circtools/files/12209245/output_circtools2_installation_R_300723.txt)

**Comment by tjakobi** [comment]
Thank you for the report @shubhada-kulkarni. It seems Microsoft retired their CRAN mirror that the script was using, which made the installation fail. I removed the hard-coded references to the mirrors and we now only use the default mirrors.

Please pull the repository and re-try the installation.

**Comment by shubhada-kulkarni** [comment]
Unfortunately, that did not work either. Is there anything else that I should check from my side that might be causing this problem?

Please find the command output in attach.
[output_circtools2_installation_R_020823.txt](https://github.com/jakobilab/circtools/files/12237022/output_circtools2_installation_R_020823.txt)

**Comment by tjakobi** [comment]
You are still using the old code, not the fixed version. Did you perform a `git pull` of *this* repository before attempting installation?

**Comment by shubhada-kulkarni** [comment]
I did `git commit` before trying the installation.
But now just to make sure, I removed all previous installations and retried using `pip install git+https://github.com/jakobilab/circtools.git --user` and it worked. Please find the command report attached.
Thanks!
[output_circtools2_installation_030823.txt](https://github.com/jakobilab/circtools/files/12248275/output_circtools2_installation_030823.txt)

**Comment by tjakobi** [comment]
`git commit` commits *your changes* to the branch/repository. You need to use `git pull` to retrieve the *remote changes*.

**Comment by shubhada-kulkarni** [comment]
My apologies, I wanted to say `git clone` and not `git commit`.

**Comment by tjakobi** [comment]
Hi @shubhada-kulkarni,

with `git clone` you are creating an entire new copy of a remote repository, which is not what you usually want, specifically if there might be local changes that you will otherwise overwrite. `git pull` will retrieve changes into an already cloned repository.

GitHub has an extensive introduction into `git`: https://docs.github.com/en/get-started/using-git/about-git
