### ISSUE TITLE
circtools issues(link not working)

### ISSUE THREAD

**Issue by mostafa99098** [jakobilab/circtools#3]
Describe the bug

I am reaching out to bring to your attention that the following link seems to be non-functional:

wget https://links.jakobilab.org/wonderdump.sh

Unfortunately, I encountered difficulties while trying to access it. Could you please assist me in resolving this issue? I am eager to access the necessary information from this link.

 - OS: [e.g. Debian 8.6, Ubuntu 18.04]
 - Python version [e.g. 3.6, 3.4]
 - Version [e.g. 1.1.0.1]

**Comment by tjakobi** [comment]
The mentioned link has been fixed. Additionally, all other links in the documentation have been reviewed as a precaution.
